#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

[ -f "$userresources" ] && xrdb -merge "$userresources"
[ -f "$usermodmap" ] && xmodmap "$usermodmap"

# run xprofile
[ -f ~/.xprofile ] && . ~/.xprofile

exec bspwm
