#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap


if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi


# start some nice programs

[ -f ~/.xprofile ] && . ~/.xprofile

exec bspwm
