export XDG_CACHE_HOME="$HOME/.cache"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"

export XINITRC="$XDG_CONFIG_HOME/X11/xinitrc"
# z
export _Z_DATA="$XDG_DATA_HOME/z"
export _Z_SRC="/usr/share/z/z.sh"
# autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5e6d6e"


# History in cache directory:
HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTFILE="$XDG_CACHE_HOME/zsh/history"

autoload -Uz compinit
if [[ -n  $XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION(#qN.mh+24) ]]
then
    compinit -d "$XDG_CACHE_HOME/zsh/zcompdump-$ZSH_VERSION"
else
    compinit -C
fi

setopt histexpiredupsfirst histignorespace nobanghist nobeep
# setopt sharehistory                 # share history between sessions
# setopt incappendhistory             # append history at same time, not at shell exits

# startx
if [ "$(tty)" = "/dev/tty1" ]
then
    pgrep bspwm || startx
fi

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
setopt auto_cd

# Include hidden files.
_comp_options+=(globdots)

# aliases
alias -g -- --help="--help | less -FXi ; true "
source $XDG_CONFIG_HOME/alias_and_keybinds/aliasrc
# load keybinds
source $XDG_CONFIG_HOME/alias_and_keybinds/key-bindings.zsh

# plugins
eval "$(starship init zsh)"
source $_Z_SRC
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
