# History in cache directory:
HISTSIZE=10000
SAVEHIST=$HISTSIZE
HISTFILE="$HOME/.cache/zsh/history"

autoload -Uz compinit
compinit -d "$HOME/.cache/zsh/zcompdump-$ZSH_VERSION"

setopt histexpiredupsfirst histignorespace nobanghist nobeep
# setopt sharehistory                 # share history between sessions
# setopt incappendhistory             # append history at same time, not at shell exits

# startx
if [ "$(tty)" = "/dev/tty1" ]
then
    pgrep bspwm || startx
fi

# z
export _Z_DATA="$HOME/.local/share/z"
export _Z_SRC="/usr/share/z/z.sh"

# autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5e6d6e"

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
setopt auto_cd

# Include hidden files.
_comp_options+=(globdots)

# aliases
alias -g -- --help="--help | less -FXi ; true "
source $HOME/.config/alias_and_keybinds/aliasrc
# load keybinds
source $HOME/.config/alias_and_keybinds/key-bindings.zsh

# plugins
eval "$(starship init zsh)"
source $_Z_SRC
source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

