# History in cache directory:
HISTSIZE=10000
SAVEHIST=10000
HISTFILE=~/.cache/zsh/history

# startx
if [ "$(tty)" = "/dev/tty1" ]
then
		pgrep bspwm || startx
fi

# zplug
export ZPLUG_HOME="$HOME/.config/.zplug"
source ~/.config/.zplug/init.zsh

# Plugins
zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "denysdovhan/spaceship-prompt", use:spaceship.zsh, from:github, as:theme
zplug "rupa/z"

# z
export _Z_DATA="$HOME/.config/.z"
source ~/.config/.zplug/repos/rupa/z/z.sh

# autosuggestions
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=#5e6d6e"

# spaceship 
SPACESHIP_PROMPT_ORDER=(
  user          # Username section
  dir           # Current directory section
  host          # Hostname section
  git           # Git section (git_branch + git_status)
  # hg            # Mercurial section (hg_branch  + hg_status)
  # package       # Package version
  # node          # Node.js section
  # ruby          # Ruby section
  # elixir        # Elixir section
  # xcode         # Xcode section
  # swift         # Swift section
  # golang        # Go section
  # php           # PHP section
  # rust          # Rust section
  # haskell       # Haskell Stack section
  # julia         # Julia section
  # docker        # Docker section
  # aws           # Amazon Web Services section
  venv          # virtualenv section
  # conda         # conda virtualenv section
  # pyenv         # Pyenv section
  # dotnet        # .NET section
  # ember         # Ember.js section
  # kubectl       # Kubectl context section
  # terraform     # Terraform workspace section
  line_sep      # Line break
  # battery       # Battery level and status
  vi_mode       # Vi-mode indicator
  jobs          # Background jobs indicator
  exit_code     # Exit code section
  char          # Prompt character
)
SPACESHIP_RPROMPT_ORDER=(
  # time          # Time stamps section
  exec_time     # Execution time
)
SPACESHIP_VI_MODE_COLOR=#586e75
SPACESHIP_VI_MODE_INSERT=[i]	
SPACESHIP_VI_MODE_NORMAL=[n]	

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Then, source plugins and add commands to $PATH
zplug load 

zstyle ':completion:*' menu select
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Za-z}'
setopt auto_cd

# Include hidden files.
_comp_options+=(globdots)		

#Key bindings
bindkey "^A" beginning-of-line
bindkey "^E" end-of-line
bindkey "^L" clear-screen
bindkey "^U" backward-kill-line
bindkey "^Y" yank
bindkey '^R' history-incremental-search-backward
bindkey '^[[3~' delete-char-or-list

# Edit line in vim with ctrl-n:
autoload edit-command-line; zle -N edit-command-line
bindkey '^n' edit-command-line

# load aliases
source ~/.config/.aliasrc

# vi mode
spaceship_vi_mode_enable

# elfman
colorscript -e 18
