#!/bin/sh
while read file
do
        case "$1" in
        "d")
                mv "$file" ~/.local/share/Trash/files/ ;;
        "g")
				gimp "$file" & ;;
        "r")
                convert -rotate 90 "$file" "$file" ;;
        "R")
                convert -rotate -90 "$file" "$file" ;;
        "w")
				hsetroot -fill "$file"  -tint '#9ccfe6' ;;
        "y")
                echo -n "$file" | xclip -selection clipboard ;;
        esac
done
