#!/bin/sh
while read file
do
        case "$1" in
        "d")
				trash "$file" ;;
        "g")
				gimp "$file" & ;;
        "r")
				convert -rotate 90 "$file" "$file" ;;
        "R")
				convert -rotate -90 "$file" "$file" ;;
        "w")
				hsetroot -fill "$file"  -tint '#9ccfe6' ;;
        "x")
				hsetroot -fill "$file" ;;
        "y")
				echo -n "$file" | xclip -selection clipboard ;;
        esac
done
