#!/bin/sh
while read file
do
        case "$1" in
        "c")
                cp "$file" ~/.cache/default_wall
                dunstify "Sxiv: set as default wall"
                ;;
        "d")
                trash "$file"
                dunstify "Sxiv: trashed"
                ;;
        "g")
                gimp "$file" &
                dunstify "Sxiv: opening in gimp"
                ;;
        "p")
                readlink -fn "$file" | xclip -selection clipboard
                dunstify "Sxiv: copied path to clipboard"
                ;;
        "r")
                convert -rotate 90 "$file" "$file"
                dunstify "Sxiv: rotated 90 clockwise"
                ;;
        "R")
                convert -rotate -90 "$file" "$file"
                dunstify "Sxiv: rotated 90 anti-clockwise"
                ;;
        "t")
                hsetroot -fill "$file"  -tint '#9ccfe6'
                dunstify "Sxiv: wallpaper is set with tint"
                ;;
        "w")
                hsetroot -fill "$file"
                dunstify "Sxiv: wallpaper is set"
                ;;
        "y")
                xclip -selection clipboard -t image/png "$file"
                dunstify "Sxiv: copied image to clipboard"
                ;;
        esac
done
