#!/bin/sh
while read file
do
        fullpath=$(readlink -fn "$file")
        case "$1" in
        "c")
                cp "$fullpath" ~/.cache/default_wall
                dunstify "Sxiv: set as default wall"
                ;;
        "d")
                trash "$fullpath"
                dunstify "Sxiv: trashed"
                ;;
        "g")
                gimp "$fullpath" &
                dunstify "Sxiv: opening in gimp"
                ;;
        "p")
                echo -n "$fullpath" | xclip -selection clipboard
                dunstify "Sxiv: copied path to clipboard"
                ;;
        "r")
                convert -rotate 90 "$fullpath" "$fullpath"
                dunstify "Sxiv: rotated 90 clockwise"
                ;;
        "R")
                convert -rotate -90 "$fullpath" "$fullpath"
                dunstify "Sxiv: rotated 90 anti-clockwise"
                ;;
        "t")
                hsetroot -fill "$fullpath" -tint '#9ccfe6'
                dunstify "Sxiv: wallpaper is set with tint"
                ;;
        "w")
                hsetroot -fill "$fullpath"
                dunstify "Sxiv: wallpaper is set"
                ;;
        "y")
                xclip -selection clipboard -t image/png "$fullpath"
                dunstify "Sxiv: copied image to clipboard"
                ;;
        esac
done
