#!/bin/bash

# dictionary
pgrep -f dictionary || $TERMINAL --class=dictionary,dictionary  -e dict-search &
# terminal
pgrep -f scratchterm || $TERMINAL --class=scratchterm,scratchterm  -e $SHELL &

sleep 10
bspc_return_nodeid dictionary   /tmp/dictionary  &
bspc_return_nodeid scratchterm  /tmp/scratchterm &
