#!/bin/bash

# terminal
[ "$(ps -x | grep -c 'scratchterm')" -eq "1" ] && $TERMINAL --class=scratchterm,scratchterm  -e $SHELL &
# dictionary
[ "$(ps -x | grep -c 'dictionary')" -eq "1" ] && $TERMINAL --class=dictionary,dictionary  -e ~/.config/scripts/dict-startup.sh &

sleep 10
bspc_return_nodeid scratchterm /tmp/scratchterm
bspc_return_nodeid dictionary /tmp/dictionary
pgrep -x simplenote && bspc_return_nodeid Simplenote /tmp/simplenote
