#!/bin/bash

bspc rule -a Sxiv --one-shot desktop=\^5 follow=on
sxiv -bf "$HOME"/Pictures/wallpapers/personal/red-seems-suspicious-bro-4k-1366×768.jpg &
sxiv_pid=$!
/usr/local/bin/slock-base "$@"
kill $sxiv_pid
bspc desktop -f last
