#!/bin/bash

# Autostart
pgrep -x sxhkd > /dev/null     || sxhkd &
$HOME/.config/polybar/launch.sh &

# monitors
bspc monitor -d I II III IV V VI

# general
bspc config automatic_scheme            spiral
bspc config border_width                1
bspc config borderless_monocle          true
bspc config bottom_padding              0
bspc config focus_follows_pointer       true
bspc config gapless_monocle             true
bspc config initial_polarity            first_child
bspc config left_padding                0
bspc config pointer_action1             move
bspc config pointer_action3             resize_corner
bspc config pointer_modifier            mod4
bspc config right_padding               0
bspc config single_monocle              true
bspc config split_ratio                 0.70
bspc config top_padding                 29
bspc config window_gap                  2
# colors
bspc config focused_border_color        "#839496"
bspc config normal_border_color         "#002b36"
bspc config presel_feedback_color       "#839496"

# rules
bspc rule -a Brave-browser              desktop='^3' state=tiled
bspc rule -a Gimp                       desktop='^5' state=floating
# bspc rule -a libreoffice-startcenter    desktop='^5' state=tiled
bspc rule -a MEGAsync                                state=floating
bspc rule -a mpv                        desktop='^5' state=tiled
# bspc rule -a Soffice                    desktop='^5' state=tiled
bspc rule -a VirtualBox\ Manager        desktop='^5' state=tiled
bspc rule -a VirtualBoxVM               desktop='^6' state=fullscreen
bspc rule -a xdman-Main                 desktop='^3' state=floating
bspc rule -a Zathura                                 state=tiled
