#! /bin/sh

# Autostart
pgrep -x dunst > /dev/null     || dunst &
pgrep -x picom > /dev/null     || picom --experimental-backends --no-fading-openclose &
pgrep -x sxhkd > /dev/null     || sxhkd &
pgrep -x unclutter > /dev/null || unclutter &
$HOME/.config/polybar/launch.sh &
bg-changer random &
numlockx &
xset r rate 300 50 -b -dpms &
xsetroot -cursor_name left_ptr &

# bspwm
# monitors
bspc monitor -d I II III IV V

# general
bspc config border_width                3
bspc config bottom_padding              0
bspc config left_padding                0
bspc config right_padding               0
bspc config split_ratio                 0.58
bspc config top_padding                 41
bspc config window_gap                  5
bspc config automatic_scheme            spiral
bspc config borderless_monocle          true
bspc config focus_follows_pointer       true
bspc config gapless_monocle             true
bspc config initial_polarity            first_child
# bspc config pointer_follows_focus       true
# colors
bspc config focused_border_color        "#1F8999"
bspc config normal_border_color         "#839496"
bspc config presel_border_color         "#26E2FF"
bspc config urgent_border_color         "#B58900"

# rules
bspc rule -a Brave-browser              desktop='^3'
bspc rule -a dictionary                              state=floating sticky=on hidden=on center=on
bspc rule -a Gimp                       desktop='^5' state=floating
# bspc rule -a libreoffice-startcenter    desktop='^5' state=tiled
bspc rule -a MEGAsync                                state=floating
bspc rule -a mpv                        desktop='^5' state=tiled
bspc rule -a scratchterm                             state=floating sticky=on hidden=on center=on
# bspc rule -a Soffice                    desktop='^5' state=tiled
bspc rule -a VirtualBox\ Manager        desktop='^5'
bspc rule -a VirtualBoxVM               desktop='^5' state=fullscreen
bspc rule -a xdman-Main                 desktop='^3' state=floating
bspc rule -a Zathura                                 state=tiled

# scratchpads
$HOME/.config/scripts/scratchpads &
