config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  keepdot: false
  link_dotfile_default: nolink
  link_on_import: nolink
  longkey: false
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
    chmod: '755'
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
    chmod: '777'
  d_alias_and_keybinds:
    src: config/alias_and_keybinds
    dst: ~/.config/alias_and_keybinds
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  d_x11:
    src: config/X11
    dst: ~/.config/X11
  d_paru:
    src: config/paru
    dst: ~/.config/paru
  d_yay:
    src: config/yay
    dst: ~/.config/yay
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
    chmod: '700'
  d_gdb:
    src: config/gdb
    dst: ~/.config/gdb
  d_sxiv:
    src: config/sxiv
    dst: ~/.config/sxiv
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
    chmod: '700'
  d_htop:
    src: config/htop
    dst: ~/.config/htop
    chmod: '700'
  d_browser_extensions_backup:
    src: config/browser_extensions_backup
    dst: ~/.config/browser_extensions_backup
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    chmod: '700'
    cmpignore:
    - watch_later
    upignore:
    - watch_later
  d_newsboat:
    src: config/newsboat
    dst: ~/.config/newsboat
    cmpignore:
    - cache.db
    upignore:
    - cache.db
  f_starship.toml:
    src: config/starship.toml
    dst: ~/.config/starship.toml
  d_scripts:
    src: config/scripts
    dst: ~/.config/scripts
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_fonts:
    src: local/share/fonts
    dst: ~/.local/share/fonts
    cmpignore:
    - .uuid
    upignore:
    - .uuid
  d_kvantum:
    src: config/Kvantum
    dst: ~/.config/Kvantum
  d_mutt:
    src: config/mutt
    dst: ~/.config/mutt
    cmpignore:
    - accounts
    - .mailsynclastrun
    upignore:
    - accounts
    - .mailsynclastrun
  d_qt5ct:
    src: config/qt5ct
    dst: ~/.config/qt5ct
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
    cmpignore:
    - '*/__pycache__'
    upignore:
    - '*/__pycache__'
  d_slock:
    src: config/slock
    dst: ~/.config/slock
  d_gtk-2.0:
    src: config/gtk-2.0
    dst: ~/.config/gtk-2.0
    chmod: '700'
  d_gtk-4.0:
    src: config/gtk-4.0
    dst: ~/.config/gtk-4.0
  d_cpupower_gui:
    src: config/cpupower_gui
    dst: ~/.config/cpupower_gui
    chmod: '700'
  f_mimeapps.list:
    src: config/mimeapps.list
    dst: ~/.config/mimeapps.list
profiles:
  arch:
    dotfiles:
    - f_zshrc
    - f_bashrc
    - d_alias_and_keybinds
    - d_sxhkd
    - d_bspwm
    - d_alacritty
    - d_x11
    - d_paru
    - d_yay
    - d_picom
    - d_zathura
    - d_gdb
    - d_sxiv
    - d_gtk-3.0
    - d_htop
    - d_browser_extensions_backup
    - d_mpv
    - d_newsboat
    - f_starship.toml
    - d_scripts
    - d_polybar
    - d_dunst
    - d_fonts
    - d_kvantum
    - d_mutt
    - d_qt5ct
    - d_ranger
    - d_slock
    - d_gtk-2.0
    - d_gtk-4.0
    - d_cpupower_gui
    - f_mimeapps.list
