config:
  backup: true
  create: true
  dotpath: dotfiles
  instignore:
  - '*/README.md'
  upignore:
  - '*/README.md'
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  d_irssi:
    src: irssi
    dst: ~/.irssi
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_breeze-red:
    src: icons/Breeze-Red
    dst: ~/.icons/Breeze-Red
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  d_newsboat:
    src: config/newsboat
    dst: ~/.config/newsboat
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_plug.vim:
    src: local/share/nvim/site/autoload/plug.vim
    dst: ~/.local/share/nvim/site/autoload/plug.vim
  d_sxiv:
    src: config/sxiv
    dst: ~/.config/sxiv
  f_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  f_update-resolv-conf:
    src: etc/openvpn/update-resolv-conf
    dst: /etc/openvpn/update-resolv-conf
  f_aliasrc:
    src: config/.aliasrc
    dst: ~/.config/.aliasrc
  d_scripts:
    src: config/scripts
    dst: ~/.config/scripts
  f_xprofile:
    src: xprofile
    dst: ~/.xprofile
  f_xmodmap:
    src: Xmodmap
    dst: ~/.Xmodmap
  f_xresources:
    src: Xresources
    dst: ~/.Xresources
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
profiles:
  arch:
    dotfiles:
    - f_zshrc
    - f_bashrc
    - f_xinitrc
    - d_irssi
    - f_gitconfig
    - d_breeze-red
    - d_mpv
    - d_htop
    - d_newsboat
    - d_ranger
    - d_sxiv
    - f_pacman.conf
    - f_update-resolv-conf
    - f_aliasrc
    - d_scripts
    - f_xprofile
    - f_xmodmap
    - f_xresources
    - d_bspwm
    - d_sxhkd
    - d_polybar
    - d_dunst
    - d_alacritty
