config:
  backup: true
  create: true
  dotpath: dotfiles
  instignore:
  - '*/README.md'
  upignore:
  - '*/README.md'
dotfiles:
  f_zshrc:
    src: zshrc
    dst: ~/.zshrc
  f_bashrc:
    src: bashrc
    dst: ~/.bashrc
  f_xinitrc:
    src: xinitrc
    dst: ~/.xinitrc
  f_gitconfig:
    src: gitconfig
    dst: ~/.gitconfig
  d_mpv:
    src: config/mpv
    dst: ~/.config/mpv
    upignore:
    - watch_later
    instignore:
    - watch_later
  d_htop:
    src: config/htop
    dst: ~/.config/htop
  d_newsboat:
    src: config/newsboat
    dst: ~/.config/newsboat
    upignore:
    - cache.db
    instignore:
    - cache.db
  d_nvim:
    src: config/nvim
    dst: ~/.config/nvim
  f_plug.vim:
    src: local/share/nvim/site/autoload/plug.vim
    dst: ~/.local/share/nvim/site/autoload/plug.vim
  d_sxiv:
    src: config/sxiv
    dst: ~/.config/sxiv
  f_aliasrc:
    src: config/.aliasrc
    dst: ~/.config/.aliasrc
  d_scripts:
    src: config/scripts
    dst: ~/.config/scripts
  d_bspwm:
    src: config/bspwm
    dst: ~/.config/bspwm
  d_sxhkd:
    src: config/sxhkd
    dst: ~/.config/sxhkd
  d_polybar:
    src: config/polybar
    dst: ~/.config/polybar
  d_dunst:
    src: config/dunst
    dst: ~/.config/dunst
  d_alacritty:
    src: config/alacritty
    dst: ~/.config/alacritty
  f_gtkrc-2.0:
    src: gtkrc-2.0
    dst: ~/.gtkrc-2.0
  d_gtk-3.0:
    src: config/gtk-3.0
    dst: ~/.config/gtk-3.0
  d_zathura:
    src: config/zathura
    dst: ~/.config/zathura
  d_breeze-blue:
    src: icons/Breeze-Blue
    dst: ~/.icons/Breeze-Blue
  d_ranger:
    src: config/ranger
    dst: ~/.config/ranger
  d_picom:
    src: config/picom
    dst: ~/.config/picom
  d_dmenu:
    src: config/dmenu
    dst: ~/.config/dmenu
  d_custom:
    src: config/.zplug/repos/custom
    dst: ~/.config/.zplug/repos/custom
  d_slock:
    src: config/slock
    dst: ~/.config/slock
  f_config:
    src: config/simplenote/config
    dst: ~/.config/simplenote/config
  d_x11:
    src: config/X11
    dst: ~/.config/X11
  f_muttrc:
    src: config/mutt/muttrc
    dst: ~/.config/mutt/muttrc
profiles:
  arch:
    dotfiles:
    - f_zshrc
    - f_bashrc
    - f_xinitrc
    - f_gitconfig
    - d_mpv
    - d_htop
    - d_newsboat
    - d_sxiv
    - f_aliasrc
    - d_scripts
    - d_bspwm
    - d_sxhkd
    - d_polybar
    - d_dunst
    - d_alacritty
    - f_gtkrc-2.0
    - d_gtk-3.0
    - d_zathura
    - d_breeze-blue
    - d_ranger
    - d_picom
    - f_plug.vim
    - d_custom
    - d_slock
    - f_config
    - d_x11
    - f_muttrc
