config:
  backup: true
  create: true
  dotpath: global-dotfiles
  instignore:
  - '*/sudoers'
  - '*/profile'
  upignore:
  - '*/sudoers'
  - '*/profile'
  cmpignore:
  - '*/sudoers'
  - '*/profile'
dotfiles:
  f_pacman.conf:
    src: etc/pacman.conf
    dst: /etc/pacman.conf
  f_update-resolv-conf:
    src: etc/openvpn/update-resolv-conf
    dst: /etc/openvpn/update-resolv-conf
  d_bin:
    src: usr/local/bin
    dst: /usr/local/bin
    upignore:
    - dmenu*
    - stest
    instignore:
    - dmenu*
    - stest
  d_cron:
    src: var/spool/cron
    dst: /var/spool/cron
  f_sudoers:
    src: etc/sudoers
    dst: /etc/sudoers
  f_script.service:
    src: etc/systemd/system/script.service
    dst: /etc/systemd/system/script.service
  f_profile:
    src: etc/profile
    dst: /etc/profile
  f__dotdrop.sh-completion.zsh:
    src: usr/share/zsh/site-functions/_dotdrop.sh-completion.zsh
    dst: /usr/share/zsh/site-functions/_dotdrop.sh-completion.zsh
  f_issue:
    src: etc/issue
    dst: /etc/issue
profiles:
  arch:
    dotfiles:
    - f_pacman.conf
    - f_update-resolv-conf
    - d_bin
    - d_cron
    - f_sudoers
    - f_script.service
    - f_profile
    - f__dotdrop.sh-completion.zsh
    - f_issue
