set -g default-terminal "tmux-256color"

# open terminal in current directory
bind  c  new-window      -c "#{pane_current_path}"
bind  %  split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

# set pane selection similar to vim 
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'


# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
