format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_status\
$python\
$line_break\
$jobs\
$character"""


right_format = """
$cmd_duration"""

[character]
success_symbol = '[ 󰁔](bold green)'
error_symbol = '[ 󰁔](bold red)'


[python]
style = 'bold blue'
format = 'via [($virtualenv)]($style)'
detect_files = []
detect_extensions = []

[git_status]
ahead = "󰁝"
behind = "󰁅"

[cmd_duration]
format = '[$duration]($style) '
show_milliseconds = true
